apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: itbacep/executor-service
  newName: itbacep/executor-service
  newTag: 526d37c35328c68d6c9fc3ff16d7617d6f7d64a2
