apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: itbacep/lti-app
  newName: itbacep/lti-app
  newTag: e3b3006331abb6400c2bec861397e0cc05425d9b
