apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: itbacep/lti-app
  newName: itbacep/lti-app
  newTag: c90897d74e67cd77e9b5ee35f26fad7b9fa0f8ee
