apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../../../kubernetes-deployments/platform/
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: lti-app
  name: lti-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ../../../kubernetes-deployments/platform/
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: lti-app
    spec:
      containers:
      - env:
        - name: LTIAPP_EXAMTAKINGURLTEMPLATE
          value: https://cep.bellotapps.com/student-login?exam-id=${exam-id}&access-token=${access-token}&refresh-token=${refresh-token}&token-id=${token-id}
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_ZIPKIN_BASEURL
          value: http://zipkin:9411/
        - name: eureka.client.serviceUrl.defaultZone
          value: http://service-registry:8761/eureka/
        image: 'itbacep/lti-app:'
        name: lti-app
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
