apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../../../kubernetes-deployments/platform/
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-users
  name: postgres-users
spec:
  ports:
  - name: "35432"
    port: 35432
    targetPort: 5432
  selector:
    io.kompose.service: postgres-users
status:
  loadBalancer: {}
