apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../../../kubernetes-deployments/platform/
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: service-registry
  name: service-registry
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ../../../kubernetes-deployments/platform/
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: service-registry
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        image: 'itbacep/service-registry:'
        name: service-registry
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
status: {}
