apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
images:
- name: itbacep/users-service
  newName: itbacep/users-service
  newTag: 1.0.0-RELEASE
