apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: itbacep/playground-service
  newName: itbacep/playground-service
  newTag: 5e4c3b0f115c82cede17023d496eb32110bc9ad1
