apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: itbacep/lti-service
  newName: itbacep/lti-service
  newTag: e61142428ef9f893a204feee4fc97238ff3f301a
