apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- statefulset.yaml
images:
- name: itbacep/service-registry
  newName: itbacep/service-registry
  newTag: 7c59ceb8d4112b99cc20118a1bdd4bcda761cd03
