apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: itbacep/basic-ui
  newName: itbacep/basic-ui
  newTag: ea4dba9a01d4cd2cd994a6a1eaf3d0d8ca5971b4
